### ISSUE TITLE
💡Feature Request: Missing client methods

### ISSUE THREAD

**Issue by cnrmck** [alex-grover/neynar-next#28]
There are several client methods that are missing still.

So far, the methods covered include:
- createSigner
- deleteCast
- getChannelFeed
- getFeedForFids
- getFollowingFeed
- getSigner
- getUserByFid
- getUserByUsername
- likeCast
- postCast
- recastCast
- unlikeCast
- unrecastCast

However, there are several critical methods that are missing. These include at least:
- getCastInformation (by url or by hash) [docs](https://docs.neynar.com/reference/get-cast)
- getThread (by url or by hash) [docs](https://docs.neynar.com/reference/get-all-casts-in-thread)
- getNotifications (by user fid) [docs](https://docs.neynar.com/reference/get-user-mentions-and-replies)

**Comment by cnrmck** [comment]
I'm finishing up the day! If you can get to it that would be great

**Comment by alex-grover** [comment]
this is live in v0.2.7 - let me know if you run into any issues!

I know there are still more missing client methods, please feel free to open another issue if there are any that would be useful for you!
