### ISSUE TITLE
💡Feature Request: Support Get Reactions and Recasts

### ISSUE THREAD

**Issue by cnrmck** [alex-grover/neynar-next#38]
https://docs.neynar.com/reference/reactions-and-recasts-v1

**Comment by alex-grover** [comment]
I probably won't have time to get to this for a few days but happy to review a PR!

**Comment by alex-grover** [comment]
have a PR here, just need to spend some time cleaning up and testing https://github.com/alex-grover/neynar-next/pull/39

**Comment by alex-grover** [comment]
Released in v0.3.1! Took the simplest path to getting this released for now and used the exact type returned by the API. Happy to iterate to make this match the other APIs - let me know if this works for you or if you have suggestions for improvements!
